// Auto-generated by wolf-dev CLI (`assets publish`). Do not edit manually.
import type { AssetSeed } from "@wolfgames/client";

/** The committed lockfile, baked in as the synchronous boot seed. */
export const assetSeed = {
  version: 1,
  files: {
  },
} as const satisfies AssetSeed;

/** Lockfile-derived asset names — `assets.url()` typos fail typecheck. */
export type AssetName = keyof typeof assetSeed.files;
