// Auto-generated by wolf-dev CLI (`assets publish`). Do not edit manually.
import type { AssetSeed } from "@wolfgames/client";

/** The committed lockfile, baked in as the synchronous boot seed. */
export const assetSeed = {
  version: 1,
  files: {
    "music-match-pile.json": "music-match-pile-da83b4825b9f.json",
    "music-match-pile.mp3": "music-match-pile-b67175c259a9.mp3",
    "music-match-pile.webm": "music-match-pile-0e49c32abc4a.webm",
    "sfx-match-pile.json": "sfx-match-pile-6c1e11ff19fc.json",
    "sfx-match-pile.mp3": "sfx-match-pile-4933f365ea67.mp3",
    "sfx-match-pile.webm": "sfx-match-pile-362d4be2330d.webm",
  },
} as const satisfies AssetSeed;

/** Lockfile-derived asset names — `assets.url()` typos fail typecheck. */
export type AssetName = keyof typeof assetSeed.files;
